<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Replace this with Umbra's directory is you have a local dev version installed. Mind the trailing backlash. -->
    <!-- If you have Umbra installed through Dalamud, you can leave this as-is. -->
    <!-- Credits to Lorosia for the dynamic Umbra folder finding. -->
    <UmbraLibPath>$([System.IO.Directory]::GetDirectories($(appdata)\XIVLauncherCN\installedPlugins\Umbra\)[0])\</UmbraLibPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platforms>x64;x86</Platforms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\out\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Light</Authors>
    <Company>Light</Company>
    <Version>1.0.4.0</Version>
    <Description>Add a Umbra widget for the plugin Visibility</Description>
    <Copyright>(C)2025</Copyright>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/una-xiv/umbra</PackageProjectUrl>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Umbra">
      <HintPath>$(UmbraLibPath)Umbra.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Umbra.Common">
      <HintPath>$(UmbraLibPath)Umbra.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Umbra.Game">
      <HintPath>$(UmbraLibPath)Umbra.Game.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Una.Drawing">
      <HintPath>$(UmbraLibPath)Una.Drawing.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Dalamud">
      <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FFXIVClientStructs">
      <HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
